# Essential Numpy

## Part 2: Shape Functions

In [15]:
#
import numpy as np
#Arrays can be reshaped
array1 = np.array([[1, 2], [3, 4]])
print(array1)
print()
array1 = array1.reshape(1, 4)
print(array1)
array1 = array1.reshape(2,2)
print(array1)



[[1 2]
 [3 4]]

[[1 2 3 4]]
[[1 2]
 [3 4]]


In [16]:
print(array1.shape)
#we can flatten this weird array
array1 = np.ravel(array1)
print(array1)

(2, 2)
[1 2 3 4]


In [11]:
array1 = np.array([[1, 2], [3, 4]])
print(array1)
print()
array1 = np.reshape(array1, (1, 4))
print(array1)

print(array1.shape)

array1 = np.reshape(array1,(2,2))
print(array1)


[[1 2]
 [3 4]]

[[1 2 3 4]]
(1, 4)
[[1 2]
 [3 4]]


In [22]:
#make array1 2x2

array1 = np.array([[2, 4], [6, 8]])
print(array1)
array1 = array1.reshape(1,4)
print(array1)
array1 = np.ravel(array1)
print(array1)




[[2 4]
 [6 8]]
[[2 4 6 8]]
[2 4 6 8]


In [23]:
#transpose the rows and columns
array1 = array1.reshape(2,2)
array1 = np.transpose(array1)
print(array1)

[[2 6]
 [4 8]]
