# Essential Numpy

## Part3: Math Operators and Functions

In [5]:
import numpy as np

In [16]:
#Adding arrays
ar1 = np.array([[1,2], [3,4]])
ar1

array([[1, 2],
       [3, 4]])

In [24]:
ar2 = np.array([[5,6], [7,8]])
ar2


array([[5, 6],
       [7, 8]])

In [26]:
ar3 = ar1 + ar2
ar3

array([[ 6,  8],
       [10, 12]])

In [27]:
#arrays can be subtracted, divided, and subjected to other manipulations
ar4 = np.sqrt(ar3)
ar4

array([[2.44948974, 2.82842712],
       [3.16227766, 3.46410162]])

In [12]:
#dot product of two vectors; multiply elements an add terms
a = [1,2,3]
b = [4,5,6]
c = np.dot(a,b)
print(c)

32


In [16]:
#matrix multiplication
#Row 1: 1st row of ar1 * 1st col of ar2 adding terms; 1st row of ar1 * 2nd col of ar2, adding terms
#Row 2: 2nd row of ar1 * 1st col of art adding terms; 2nd fow of ar1 * 2nd col of ar2, adding terms
ar1 = np.array([[1,2],
               [3,4]])
ar2 = np.array([[4,5],
               [6,7]])

print(ar1)
print(ar2)
np.matmul(ar1,ar2)


[[1 2]
 [3 4]]
[[4 5]
 [6 7]]


array([[16, 19],
       [36, 43]])

In [17]:
#Matrix mult: Internal dimensions must be the same: AxC * CXD
A = np.array([[1,2,3],
          [4,5,6]])
B = np.array([ [7,8],
               [9,10],
               [11,12]])

C = np.matmul(A,B)
print(C)
print(np.shape(A))
print(np.shape(B))
print(np.shape(C))




[[ 58  64]
 [139 154]]
(2, 3)
(3, 2)
(2, 2)


In [45]:
#Two more easy ones
print(max(a))
print(min(b))
print(np.log10(100)) #base 10
print(np.log2(32)) #base 2
print(np.log(1))  #natural log

3
4
2.0
5.0
0.0
