# Essential Numpy

## Part 1 General Array Functions

In [1]:
import numpy as np

In [2]:
#Numpy arrays are like Python lists 
#1-d
arr1 = np.array([1,2,3])
arr1
print(arr1[0])


1


In [3]:
#2-d
arr2 = np.array([[10, 20, 30], [210, 220, 230]])
arr2
print(arr2[1,1])

220


In [4]:
#3-d: A stack of 2-d matrices
#First index: Which matrix (or block). There are 2--block 0 and block 1
#Second index: Which row withn a block.  There are 3: 0,1,2
#Third index: Which column within a block.  There 4: 0,1,2,3

arr3 = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],

    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])
arr3
print(arr3[1,1,2])
print(arr3[0,2,3])

19
12


In [5]:
#The shape of an array is a tuple of max sizes. In this case, 2 blocks, 3 rows, 4 colums
np.shape(arr3)

(2, 3, 4)

In [6]:
#insert function
#insert 'Q' in a new second second row by setting axis to 0
arr = np.array([['z','a','g','s'], ['h','o','o','p']])
arr = np.insert(arr,2,'Q', axis=0)
print(np.shape(arr))
print(arr)
               

(3, 4)
[['z' 'a' 'g' 's']
 ['h' 'o' 'o' 'p']
 ['Q' 'Q' 'Q' 'Q']]


In [7]:
#inster 'R in a new second column, by setting axis to 1
arr = np.array([['z','a','g','s'], ['h','o','o','p']])
arr = np.insert(arr,2,'R', axis=1)
print(np.shape(arr))
print(arr)

(2, 5)
[['z' 'a' 'R' 'g' 's']
 ['h' 'o' 'R' 'o' 'p']]


In [21]:
#sort
import random
arr = np.array([random.randint(0,100) for i in range(10)])
print(arr)
np.sort(arr)


[77 93 78 48 89 10  3 73 28  8]


array([ 3,  8, 10, 28, 48, 73, 77, 78, 89, 93])

In [28]:
#sorting a matrix by rows then cols
arr = np.array([[6,5],
      [4,2],
      [2,1]])
print(arr)
print()
arr = np.sort(arr,axis=0)
print(arr)
print()
arr = np.sort(arr,axis=1)
print(arr)



[[6 5]
 [4 2]
 [2 1]]

[[2 1]
 [4 2]
 [6 5]]

[[1 2]
 [2 4]
 [5 6]]


In [30]:
#delete row 0.
arr = np.delete(arr,0, axis=0)
print(arr)

[[2 4]
 [5 6]]


In [34]:
#Creaete an array with zeros
np.zeros(3)
print()
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Part 2: Shape Functions

In [40]:
#Arrays can be reshaped
array1 = np.array([[1, 2], [3, 4]])
print(array1)
print()
array1 = np.reshape(array1, (1, 4))
print(array1)

[[1 2]
 [3 4]]

[[1 2 3 4]]


In [43]:
#we can flatten this weird array
array1 = np.ravel(array1)
print(array1)

[1 2 3 4]


In [45]:
#make array1 2x2
array1 = np.resize(array1,(2,2))
print(array1)

[[1 2]
 [3 4]]


In [46]:
#transpose the rows and columns
array1 = np.transpose(array1)
print(array1)

[[1 3]
 [2 4]]


## Part3: Math operators and functions